"""new tables

Revision ID: 2806a811685f
Revises: fad1dc847283
Create Date: 2025-10-01 12:51:48.892756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2806a811685f'
down_revision: Union[str, Sequence[str], None] = 'fad1dc847283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_of_organisation', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_contact_person'), 'client', ['contact_person'], unique=False)
    op.create_index(op.f('ix_client_country'), 'client', ['country'], unique=False)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_name_of_organisation'), 'client', ['name_of_organisation'], unique=False)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=False)
    op.create_index(op.f('ix_client_sector'), 'client', ['sector'], unique=False)
    op.create_table('hamasa_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender', create_type=False), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('super_admin', 'reviewer', 'data_clerk', 'org_admin', 'org_user', name='userrole', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_hamasa_users_email'), 'hamasa_users', ['email'], unique=True)
    op.create_index(op.f('ix_hamasa_users_first_name'), 'hamasa_users', ['first_name'], unique=False)
    op.create_index(op.f('ix_hamasa_users_is_active'), 'hamasa_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_hamasa_users_last_name'), 'hamasa_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_hamasa_users_phone_number'), 'hamasa_users', ['phone_number'], unique=True)
    op.create_table('client_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_index(op.f('ix_client_users_phone_number'), 'client_users', ['phone_number'], unique=True)
    op.create_table('hamasa_user_client_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hamasa_user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hamasa_user_id'], ['hamasa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hamasa_user_id', 'client_id', name='uq_hamasa_user_client'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hamasa_user_client_assignments')
    op.drop_index(op.f('ix_client_users_phone_number'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_index(op.f('ix_hamasa_users_phone_number'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_last_name'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_is_active'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_first_name'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_email'), table_name='hamasa_users')
    op.drop_table('hamasa_users')
    op.drop_index(op.f('ix_client_sector'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_name_of_organisation'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index(op.f('ix_client_country'), table_name='client')
    op.drop_index(op.f('ix_client_contact_person'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
