"""new user table

Revision ID: 32314027aa7c
Revises: 2806a811685f
Create Date: 2025-10-01 16:14:31.106045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32314027aa7c'
down_revision: Union[str, Sequence[str], None] = '2806a811685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['id'])
    op.create_unique_constraint(None, 'client_users', ['id'])
    op.create_unique_constraint(None, 'hamasa_user_client_assignments', ['id'])
    op.alter_column('hamasa_users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=True)
    op.create_unique_constraint(None, 'hamasa_users', ['id'])
    op.drop_column('hamasa_users', 'dob')
    op.drop_column('hamasa_users', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hamasa_users', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hamasa_users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hamasa_users', type_='unique')
    op.alter_column('hamasa_users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=False)
    op.drop_constraint(None, 'hamasa_user_client_assignments', type_='unique')
    op.drop_constraint(None, 'client_users', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
