"""added password to client user table

Revision ID: 65a0ca562837
Revises: 32314027aa7c
Create Date: 2025-10-01 16:39:49.022712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a0ca562837'
down_revision: Union[str, Sequence[str], None] = '32314027aa7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_users', 'hashed_password')
    # ### end Alembic commands ###
