"""updated the thematic areas table

Revision ID: 853ca44692c6
Revises: 65a0ca562837
Create Date: 2025-10-09 14:57:53.595705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853ca44692c6'
down_revision: Union[str, Sequence[str], None] = '65a0ca562837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_report_avenues', sa.Column('report_avenue_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('project_report_avenues_avenue_id_fkey'), 'project_report_avenues', type_='foreignkey')
    op.drop_constraint(op.f('project_report_avenues_project_id_fkey'), 'project_report_avenues', type_='foreignkey')
    op.create_foreign_key(None, 'project_report_avenues', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_report_avenues', 'report_avenues', ['report_avenue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_report_avenues', 'avenue_id')
    op.add_column('project_report_consultations', sa.Column('report_consultation_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('project_report_consultations_consultation_id_fkey'), 'project_report_consultations', type_='foreignkey')
    op.drop_constraint(op.f('project_report_consultations_project_id_fkey'), 'project_report_consultations', type_='foreignkey')
    op.create_foreign_key(None, 'project_report_consultations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_report_consultations', 'report_consultations', ['report_consultation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_report_consultations', 'consultation_id')
    op.add_column('project_report_times', sa.Column('report_time_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('project_report_times_time_id_fkey'), 'project_report_times', type_='foreignkey')
    op.drop_constraint(op.f('project_report_times_project_id_fkey'), 'project_report_times', type_='foreignkey')
    op.create_foreign_key(None, 'project_report_times', 'report_times', ['report_time_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_report_times', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_report_times', 'time_id')
    op.add_column('project_thematic_areas', sa.Column('title', sa.String(), nullable=False, server_default='Untitled'))
    op.add_column('project_thematic_areas', sa.Column('description', sa.String(), nullable=True))
    op.add_column('project_thematic_areas', sa.Column('monitoring_objective', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_thematic_areas', 'monitoring_objective')
    op.drop_column('project_thematic_areas', 'description')
    op.drop_column('project_thematic_areas', 'title')
    op.add_column('project_report_times', sa.Column('time_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_report_times', type_='foreignkey')
    op.drop_constraint(None, 'project_report_times', type_='foreignkey')
    op.create_foreign_key(op.f('project_report_times_project_id_fkey'), 'project_report_times', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_report_times_time_id_fkey'), 'project_report_times', 'report_times', ['time_id'], ['id'])
    op.drop_column('project_report_times', 'report_time_id')
    op.add_column('project_report_consultations', sa.Column('consultation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_report_consultations', type_='foreignkey')
    op.drop_constraint(None, 'project_report_consultations', type_='foreignkey')
    op.create_foreign_key(op.f('project_report_consultations_project_id_fkey'), 'project_report_consultations', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_report_consultations_consultation_id_fkey'), 'project_report_consultations', 'report_consultations', ['consultation_id'], ['id'])
    op.drop_column('project_report_consultations', 'report_consultation_id')
    op.add_column('project_report_avenues', sa.Column('avenue_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_report_avenues', type_='foreignkey')
    op.drop_constraint(None, 'project_report_avenues', type_='foreignkey')
    op.create_foreign_key(op.f('project_report_avenues_project_id_fkey'), 'project_report_avenues', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_report_avenues_avenue_id_fkey'), 'project_report_avenues', 'report_avenues', ['avenue_id'], ['id'])
    op.drop_column('project_report_avenues', 'report_avenue_id')
    # ### end Alembic commands ###
