"""added client table

Revision ID: 9f59de0534f4
Revises: 762632b522f8
Create Date: 2025-09-30 12:33:01.888792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9f59de0534f4'
down_revision: Union[str, Sequence[str], None] = '762632b522f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_of_organisation', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_contact_person'), 'client', ['contact_person'], unique=False)
    op.create_index(op.f('ix_client_country'), 'client', ['country'], unique=False)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_name_of_organisation'), 'client', ['name_of_organisation'], unique=False)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=False)
    op.create_index(op.f('ix_client_sector'), 'client', ['sector'], unique=False)
    op.create_table('user_client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_foreign_key(None, 'users', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'client_id')
    op.drop_table('user_client')
    op.drop_index(op.f('ix_client_sector'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_name_of_organisation'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index(op.f('ix_client_country'), table_name='client')
    op.drop_index(op.f('ix_client_contact_person'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
