"""fixed relationships bt user and clients

Revision ID: e8356dfc215d
Revises: 9f59de0534f4
Create Date: 2025-09-30 12:43:29.050257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8356dfc215d'
down_revision: Union[str, Sequence[str], None] = '9f59de0534f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['id'])
    op.add_column('user_client', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('user_client', sa.Column('client_id', sa.UUID(), nullable=False))
    op.add_column('user_client', sa.Column('date_joined', sa.DateTime(), nullable=False))
    op.add_column('user_client', sa.Column('role_within_client', sa.String(), nullable=True))
    op.add_column('user_client', sa.Column('is_primary_contact', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user_client', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_client', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_client', 'id')
    op.drop_constraint(op.f('users_client_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_client_id_fkey'), 'users', 'client', ['client_id'], ['id'])
    op.add_column('user_client', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_client', type_='foreignkey')
    op.drop_constraint(None, 'user_client', type_='foreignkey')
    op.drop_column('user_client', 'is_primary_contact')
    op.drop_column('user_client', 'role_within_client')
    op.drop_column('user_client', 'date_joined')
    op.drop_column('user_client', 'client_id')
    op.drop_column('user_client', 'user_id')
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
