"""added is_dleted to client_user table

Revision ID: 488339ba5fb1
Revises: 0de293ed8f48
Create Date: 2025-11-19 15:21:33.686207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488339ba5fb1'
down_revision: Union[str, Sequence[str], None] = '0de293ed8f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_users', 'is_deleted')
    # ### end Alembic commands ###
