"""added cretated at and updated at to client table

Revision ID: 56ce18fcc923
Revises: 604211c21989
Create Date: 2025-11-18 20:49:41.910880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ce18fcc923'
down_revision: Union[str, Sequence[str], None] = '604211c21989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('client', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'client', ['id'])
    op.create_unique_constraint(None, 'client_users', ['id'])
    op.create_unique_constraint(None, 'hamasa_user_client_assignments', ['id'])
    op.create_unique_constraint(None, 'hamasa_users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hamasa_users', type_='unique')
    op.drop_constraint(None, 'hamasa_user_client_assignments', type_='unique')
    op.drop_constraint(None, 'client_users', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_column('client', 'is_deleted')
    op.drop_column('client', 'updated_at')
    op.drop_column('client', 'created_at')
    op.drop_table('ml_analysis_results')
    # ### end Alembic commands ###
