"""initial migration

Revision ID: 604211c21989
Revises: 
Create Date: 2025-11-14 14:56:30.800372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '604211c21989'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_of_organisation', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_contact_person'), 'client', ['contact_person'], unique=False)
    op.create_index(op.f('ix_client_country'), 'client', ['country'], unique=False)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=False)
    op.create_index(op.f('ix_client_name_of_organisation'), 'client', ['name_of_organisation'], unique=False)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=False)
    op.create_index(op.f('ix_client_sector'), 'client', ['sector'], unique=False)
    op.create_table('hamasa_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('super_admin', 'reviewer', 'data_clerk', 'org_admin', 'org_user', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_hamasa_users_email'), 'hamasa_users', ['email'], unique=True)
    op.create_index(op.f('ix_hamasa_users_first_name'), 'hamasa_users', ['first_name'], unique=False)
    op.create_index(op.f('ix_hamasa_users_is_active'), 'hamasa_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_hamasa_users_last_name'), 'hamasa_users', ['last_name'], unique=False)
    op.create_index(op.f('ix_hamasa_users_phone_number'), 'hamasa_users', ['phone_number'], unique=True)
    op.create_table('media_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_thematic_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monitoring_objective', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_avenues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_times',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_client_users_email'), 'client_users', ['email'], unique=True)
    op.create_index(op.f('ix_client_users_phone_number'), 'client_users', ['phone_number'], unique=True)
    op.create_table('hamasa_user_client_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hamasa_user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hamasa_user_id'], ['hamasa_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hamasa_user_id', 'client_id', name='uq_hamasa_user_client'),
    sa.UniqueConstraint('id')
    )
    op.create_table('media_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['media_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'review', 'in_progress', 'active', 'completed', 'archived', name='projectstatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('project_category',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_category_id'], ['project_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'project_category_id')
    )
    op.create_table('project_collaborators',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collaborator_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collaborator_id'], ['client_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'collaborator_id')
    )
    op.create_table('project_media_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('media_source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_source_id'], ['media_sources.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_report_avenues',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_avenue_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_avenue_id'], ['report_avenues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'report_avenue_id')
    )
    op.create_table('project_report_consultations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_consultation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_consultation_id'], ['report_consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'report_consultation_id')
    )
    op.create_table('project_report_times',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_time_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_time_id'], ['report_times.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'report_time_id')
    )
    op.create_table('project_thematic_area',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_thematic_area_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_thematic_area_id'], ['project_thematic_areas.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'project_thematic_area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_thematic_area')
    op.drop_table('project_report_times')
    op.drop_table('project_report_consultations')
    op.drop_table('project_report_avenues')
    op.drop_table('project_media_sources')
    op.drop_table('project_collaborators')
    op.drop_table('project_category')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('media_sources')
    op.drop_table('hamasa_user_client_assignments')
    op.drop_index(op.f('ix_client_users_phone_number'), table_name='client_users')
    op.drop_index(op.f('ix_client_users_email'), table_name='client_users')
    op.drop_table('client_users')
    op.drop_table('report_times')
    op.drop_table('report_consultations')
    op.drop_table('report_avenues')
    op.drop_table('project_thematic_areas')
    op.drop_table('project_categories')
    op.drop_table('media_categories')
    op.drop_index(op.f('ix_hamasa_users_phone_number'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_last_name'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_is_active'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_first_name'), table_name='hamasa_users')
    op.drop_index(op.f('ix_hamasa_users_email'), table_name='hamasa_users')
    op.drop_table('hamasa_users')
    op.drop_index(op.f('ix_client_sector'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_name_of_organisation'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index(op.f('ix_client_country'), table_name='client')
    op.drop_index(op.f('ix_client_contact_person'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
