"""added descriptions to category table

Revision ID: ae6aa4101763
Revises: 6a02ac3e58d4
Create Date: 2025-11-19 20:47:24.605241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6aa4101763'
down_revision: Union[str, Sequence[str], None] = '6a02ac3e58d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_categories', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_categories', 'description')
    # ### end Alembic commands ###
