"""added timestamps and is_deleted

Revision ID: d44e505ec078
Revises: eebc37f00f01
Create Date: 2025-11-19 17:20:57.488518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44e505ec078'
down_revision: Union[str, Sequence[str], None] = 'eebc37f00f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('media_categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('media_categories', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('media_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('media_sources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('media_sources', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_categories', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_media_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_media_sources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_media_sources', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('project_thematic_areas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_thematic_areas', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_thematic_areas', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('report_avenues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('report_avenues', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report_avenues', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('report_consultations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('report_consultations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report_consultations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('report_times', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('report_times', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('report_times', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_times', 'is_deleted')
    op.drop_column('report_times', 'updated_at')
    op.drop_column('report_times', 'created_at')
    op.drop_column('report_consultations', 'is_deleted')
    op.drop_column('report_consultations', 'updated_at')
    op.drop_column('report_consultations', 'created_at')
    op.drop_column('report_avenues', 'is_deleted')
    op.drop_column('report_avenues', 'updated_at')
    op.drop_column('report_avenues', 'created_at')
    op.drop_column('project_thematic_areas', 'is_deleted')
    op.drop_column('project_thematic_areas', 'updated_at')
    op.drop_column('project_thematic_areas', 'created_at')
    op.drop_column('project_media_sources', 'is_deleted')
    op.drop_column('project_media_sources', 'updated_at')
    op.drop_column('project_media_sources', 'created_at')
    op.drop_column('project_categories', 'is_deleted')
    op.drop_column('project_categories', 'updated_at')
    op.drop_column('project_categories', 'created_at')
    op.drop_column('media_sources', 'is_deleted')
    op.drop_column('media_sources', 'updated_at')
    op.drop_column('media_sources', 'created_at')
    op.drop_column('media_categories', 'is_deleted')
    op.drop_column('media_categories', 'updated_at')
    op.drop_column('media_categories', 'created_at')
    # ### end Alembic commands ###
