"""removed sector column from client tables

Revision ID: ea3af11f4f14
Revises: 8b6ed5f14425
Create Date: 2025-11-19 12:21:35.130253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3af11f4f14'
down_revision: Union[str, Sequence[str], None] = '8b6ed5f14425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_sector'), table_name='client')
    op.drop_column('client', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_client_sector'), 'client', ['sector'], unique=False)
    # ### end Alembic commands ###
