"""added description column to Category table

Revision ID: eebc37f00f01
Revises: 488339ba5fb1
Create Date: 2025-11-19 17:01:48.784088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebc37f00f01'
down_revision: Union[str, Sequence[str], None] = '488339ba5fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_categories', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_categories', 'description')
    # ### end Alembic commands ###
